name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'utilx/**'
      - 'online_retails/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get commit hash
      id: commit
      uses: pr-mpt/actions-commit-hash@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./online_retails/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/online_retails_flow:${{ steps.commit.outputs.short }}
